name: PinataFest
version: '${version}'
main: dev.pinatafest.PinataFestPlugin
api-version: '1.21'
description: Vote rewards and pinata parties for Votifier servers.
authors:
  - Groovified

dependencies:
  server:
    Votifier:
      load: BEFORE
      required: false
      join-classpath: true
    NuVotifier:
      load: BEFORE
      required: false
      join-classpath: true
    VotifierPlus:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
